// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.domain.facet;

import com.searchbox.domain.facet.FieldFacet;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect FieldFacet_Roo_Configurable {
    
    declare @type: FieldFacet: @Configurable;
    
}
