// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.domain.facet;

import com.searchbox.domain.facet.FieldFacet;

privileged aspect FieldFacet_Roo_JavaBean {
    
    public String FieldFacet.getFieldName() {
        return this.fieldName;
    }
    
    public void FieldFacet.setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }
    
}
