// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.domain;

import com.searchbox.domain.AccountBean;
import java.io.Serializable;

privileged aspect AccountBean_Roo_Serializable {
    
    declare parents: AccountBean implements Serializable;
    
    private static final long AccountBean.serialVersionUID = 1L;
    
}
