// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.domain;

import com.searchbox.domain.Collection;

privileged aspect Collection_Roo_JavaBean {
    
    public String Collection.getName() {
        return this.name;
    }
    
    public void Collection.setName(String name) {
        this.name = name;
    }
    
}
