// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.domain;

import com.searchbox.domain.FieldBean;
import java.io.Serializable;

privileged aspect FieldBean_Roo_Serializable {
    
    declare parents: FieldBean implements Serializable;
    
    private static final long FieldBean.serialVersionUID = 1L;
    
}
