// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.domain;

import com.searchbox.domain.FieldDefinition;
import javax.persistence.Entity;

privileged aspect FieldDefinition_Roo_Jpa_Entity {
    
    declare @type: FieldDefinition: @Entity;
    
}
