// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.domain;

import com.searchbox.domain.PresetDefinition;
import javax.persistence.Entity;

privileged aspect PresetDefinition_Roo_Jpa_Entity {
    
    declare @type: PresetDefinition: @Entity;
    
    public PresetDefinition.new() {
        super();
    }

}
