// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.domain;

import com.searchbox.domain.SolrCollectionBean;
import java.io.Serializable;

privileged aspect SolrCollectionBean_Roo_Serializable {
    
    declare parents: SolrCollectionBean implements Serializable;
    
    private static final long SolrCollectionBean.serialVersionUID = 1L;
    
}
