// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.domain.collection;

import com.searchbox.domain.collection.SolrCloudCollection;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SolrCloudCollection_Roo_Configurable {
    
    declare @type: SolrCloudCollection: @Configurable;
    
}
