// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.domain.collection;

import com.searchbox.domain.collection.SolrCloudCollection;
import javax.persistence.Entity;

privileged aspect SolrCloudCollection_Roo_Jpa_Entity {
    
    declare @type: SolrCloudCollection: @Entity;
    
}
