// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.domain.collection;

import com.searchbox.domain.collection.SolrCollection;
import javax.persistence.Entity;

privileged aspect SolrCollection_Roo_Jpa_Entity {
    
    declare @type: SolrCollection: @Entity;
    
}
