// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.domain.engine;

import com.searchbox.domain.engine.SearchEngine;

privileged aspect SearchEngine_Roo_JavaBean {
    
    public String SearchEngine.getZkHost() {
        return this.zkHost;
    }
    
    public void SearchEngine.setZkHost(String zkHost) {
        this.zkHost = zkHost;
    }
    
}
