// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.domain.engine;

import com.searchbox.domain.engine.SolrCloudEngine;
import javax.persistence.Entity;

privileged aspect SolrCloudEngine_Roo_Jpa_Entity {
    
    declare @type: SolrCloudEngine: @Entity;
    
}
