// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.domain.engine;

import com.searchbox.domain.engine.SolrEngine;

privileged aspect SolrEngine_Roo_JavaBean {
    
    public String SolrEngine.getSolrHost() {
        return this.solrHost;
    }
    
    public void SolrEngine.setSolrHost(String solrHost) {
        this.solrHost = solrHost;
    }
    
}
