// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.core.dm;

import com.searchbox.core.dm.Field;

privileged aspect Field_Roo_JavaBean {
    
    public Class Field.getClazz() {
        return this.clazz;
    }
    
    public void Field.setClazz(Class clazz) {
        this.clazz = clazz;
    }
    
}
