// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.domain.app;

import com.searchbox.domain.app.SearchElementDefinitionAttribute;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SearchElementDefinitionAttribute_Roo_Configurable {
    
    declare @type: SearchElementDefinitionAttribute: @Configurable;
    
}
