// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.domain.converter;

import com.searchbox.domain.converter.FieldFacetConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect FieldFacetConverter_Roo_Configurable {
    
    declare @type: FieldFacetConverter: @Configurable;
    
}
