// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.domain.app.facet;

import com.searchbox.domain.app.facet.FieldFacetDefinition;
import javax.persistence.Entity;

privileged aspect FieldFacetDefinition_Roo_Jpa_Entity {
    
    declare @type: FieldFacetDefinition: @Entity;
    
    public FieldFacetDefinition.new() {
        super();
    }

}
