// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.domain.app.facet;

import com.searchbox.domain.app.facet.FieldFacetDefinition;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect FieldFacetDefinition_Roo_Configurable {
    
    declare @type: FieldFacetDefinition: @Configurable;
    
}
