// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.searchbox.domain.app.facet;

import com.searchbox.domain.app.facet.RangeFacetDefinition;
import javax.persistence.Entity;

privileged aspect RangeFacetDefinition_Roo_Jpa_Entity {
    
    declare @type: RangeFacetDefinition: @Entity;
    
}
